name: trpg
channels:
  - defaults
dependencies:
  - python=3.7.6
  - pip:
    - aiohttp==3.6.2
    - async-timeout==3.0.1
    - attrs==19.3.0
    - cachetools==4.1.0
    - certifi==2020.4.5.1
    - chardet==3.0.4
    - discord.py==1.4.1
    - google-auth==1.14.1
    - google-auth-oauthlib==0.4.1
    - gspread==3.6.0
    - httplib2==0.17.3
    - idna==2.9
    - multidict==4.7.5
    - numpy==1.18.4
    - oauth2client==4.1.3
    - oauthlib==3.1.0
    - parse==1.15.0
    - pyasn1==0.4.8
    - pyasn1-modules==0.2.8
    - requests==2.23.0
    - requests-oauthlib==1.3.0
    - rsa==4.0
    - six==1.14.0
    - urllib3==1.25.9
    - websockets==8.1
    - wincertstore==0.2
    - yarl==1.4.2
